#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

readonly devices_file=/tmp/.devices

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
	uci commit
}

autelan_at_ctrl() {
        local info=$1
        local model_3g=$2
        local ttyUSB_infer=$3; shift 3

        AT_RETURN=$(/bin/cat ${devices_file} | /bin/grep "${info}")      
        if [ "$AT_RETURN" ]; then                                                        
                echo "${model_3g}" > /tmp/3g_model
                ln -sf ${ttyUSB_infer} /usr/sbin/at_ctrl                            
                return                                                                                 
        fi
}

autelan_func() {
	PRODUCT_INFO=/tmp/.productinfo
	
	if [ -f "$PRODUCT_INFO" ]; then
        	cat "$PRODUCT_INFO"
	else
		local mac=$(/usr/bin/partool -part mtd7 -show product.mac | sed 's/://g')
		ifconfig eth0 hw ether "$mac"
                local mac_1=` echo $mac | awk -F '' '{print $1$2$3$4$5$6}' `
                local mac_2=` echo $mac | awk -F '' '{print $7$8$9$10$11$12}' `
		local mac1="$mac_1""$(awk 'BEGIN{printf("%06x",'0x$mac_2'+'0x000001')}')"
                ifconfig eth1 hw ether "$mac1"
		
		local model sn vendor
		vendor=$(/usr/bin/partool -part mtd7 -show product.vendor)
		model=$(/usr/bin/partool -part mtd7 -show product.model)
		sn=$(/usr/bin/partool -part mtd7 -show product.sn)
		
		[ -n "$mac" ] && echo "MAC:$mac"   	>>  "$PRODUCT_INFO"
		[ -n "$sn" ] && echo "SN:$sn"			>> "$PRODUCT_INFO"
		[ -n "$vendor" ] && echo "Vendor:$vendor"	>>  "$PRODUCT_INFO"
		[ -n "$model" ] && echo "Model:$model"		>> "$PRODUCT_INFO"
	fi
	                                                                                   
	rm -r /usr/sbin/at_ctrl
        /bin/cat /sys/kernel/debug/usb/devices > ${devices_file}

        autelan_at_ctrl "Vendor=19d2 ProdID=ffed" "MC271X" "/usr/sbin/at_ttyUSB1"
        autelan_at_ctrl "Vendor=1435 ProdID=d111" "DM111" "/usr/sbin/at_ttyUSB1"
        autelan_at_ctrl "Vendor=05c6 ProdID=9000" "SIM6320C" "/usr/sbin/at_ttyUSB3"
        autelan_at_ctrl "Vendor=1c9e ProdID=9e00" "C5300V" "/usr/sbin/at_ttyUSB3"
        autelan_at_ctrl "Vendor=1c9e ProdID=9b05" "U8300C" "/usr/sbin/at_ttyUSB2"

        rm -f ${devices_file}
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/tftp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	# allow wifi modules time to settle
	sleep 1

	/sbin/wifi detect > /tmp/wireless.tmp
	[ -s /tmp/wireless.tmp ] && {
		cat /tmp/wireless.tmp >> /etc/config/wireless
	}
	rm -f /tmp/wireless.tmp

	/bin/board_detect
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config

	autelan_func

	# create /dev/root if it doesn't exist
	[ -e /dev/root -o -h /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}
}
