#!/bin/bash

. ${__ROOTFS__}/etc/utils/utils.in

#
#$1:on/off
#
main() {
	local state="$1"
	local value

	ap_board_check || return

	case ${state} in
	on)
		value=1
		;;
	off)
		value=0
		;;
	*)
		return ${e_inval}
		;;
	esac

	echo ${value} > /sys/class/leds/db120\:green\:alarm/brightness
}

main "$@"
