#!/bin/sh

. /sbin/autelan_functions.in

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

if [ "$INTERFACE" = "evdo" ]; then
	[ -f /tmp/.${INTERFACE} ] && logger "$0: due to $ACTION of $INTERFACE, 20-firewall exit" && exit 0
	create_3g_firewall_flag
fi
/etc/init.d/firewall enabled || exit 0

fw3 -q network "$INTERFACE" >/dev/null || exit 0

logger -t firewall "Reloading firewall due to $ACTION of $INTERFACE ($DEVICE)"
fw3 -q reload
